Update custom-elements.json
christianliebel/paint pull request #597
Opened 2022-02-27 07:37 UTC by jogibear9988

fix to match spec

2022-02-27 09:31 UTC, christianliebel requested changes
I guess this needs to relate to the build location in the final package?

2022-02-27 09:31 UTC, christianliebel commented on custom-elements.json
> +      "path": "index.js",
```suggestion
      "path": "dist/elements/index.js",
```

2022-02-27 09:31 UTC, christianliebel commented on custom-elements.json
> +            "module": "index.js"
```suggestion
            "module": "dist/elements/index.js"
```

2022-02-27 11:34 UTC, jogibear9988 commented
I think the index.js would also work, cause it exports everything. But your index is in the dist dir.... my fault.

2022-02-27 11:35 UTC, jogibear9988 commented
I'm currently workin on a manifest loader for my designer, so I'm looking for components using the manifest, and try to fix :-)

2022-02-27 11:43 UTC, christianliebel approved these changes

2022-02-27 11:45 UTC, christianliebel commented
LGTM, could you please squash your commits and rename the final commit to something like `fix(custom-elements): update manifest to match spec`? I'm using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) here. Thanks for your support!

2022-02-28 06:53 UTC, jogibear9988 commented
@christianliebel 
squashed and renamed.

could you create a new npm when you merge? so I could test if it works?

2022-02-28 07:02 UTC, merged

2022-02-28 07:15 UTC, christianliebel commented
> @christianliebel squashed and renamed.
> 
> could you create a new npm when you merge? so I could test if it works?

Done!

2022-02-28 07:20 UTC, jogibear9988 commented
thx